//go:build windows

package bindings

const (
	SIMCONNECT_UNUSED                  = uint32(0xFFFFFFFF)
	SIMCONNECT_OBJECT_ID_MAX           = uint32(0xFFFFFFFF) - 128
	SIMCONNECT_OBJECT_ID_USER          = uint32(0)
	SIMCONNECT_OBJECT_ID_USER_AIRCRAFT = uint32(0)
	SIMCONNECT_OBJECT_ID_USER_AVATAR   = SIMCONNECT_OBJECT_ID_MAX + 1
	SIMCONNECT_OBJECT_ID_USER_CURRENT  = SIMCONNECT_OBJECT_ID_MAX + 2

	SIMCONNECT_CLIENTDATA_MAX_SIZE = uint32(8192)

	SIMCONNECT_CAMERA_IGNORE_FIELD = float32(3.4028234663852886e+38)

	SIMCONNECT_GROUP_PRIORITY_HIGHEST          = uint32(1)
	SIMCONNECT_GROUP_PRIORITY_HIGHEST_MASKABLE = uint32(10000000)
	SIMCONNECT_GROUP_PRIORITY_STANDARD         = uint32(1900000000)
	SIMCONNECT_GROUP_PRIORITY_DEFAULT          = uint32(2000000000)
	SIMCONNECT_GROUP_PRIORITY_LOWEST           = uint32(4000000000)

	MAX_METAR_LENGTH = uint32(2000)
	MAX_THERMAL_SIZE = float32(100000)
	MAX_THERMAL_RATE = float32(1000)

	// AddToClientDataDefinition dwSizeOrType special values (stored as DWORD, so cast from -N)
	SIMCONNECT_CLIENTDATATYPE_INT8    = ^uint32(0) // -1
	SIMCONNECT_CLIENTDATATYPE_INT16   = ^uint32(1) // -2
	SIMCONNECT_CLIENTDATATYPE_INT32   = ^uint32(2) // -3
	SIMCONNECT_CLIENTDATATYPE_INT64   = ^uint32(3) // -4
	SIMCONNECT_CLIENTDATATYPE_FLOAT32 = ^uint32(4) // -5
	SIMCONNECT_CLIENTDATATYPE_FLOAT64 = ^uint32(5) // -6

	SIMCONNECT_CLIENTDATAOFFSET_AUTO  = ^uint32(0) // -1
	SIMCONNECT_OPEN_CONFIGINDEX_LOCAL = ^uint32(0) // -1

	// INITPOSITION airspeed special values
	INITPOSITION_AIRSPEED_CRUISE = ^uint32(0) // -1
	INITPOSITION_AIRSPEED_KEEP   = ^uint32(1) // -2

	SIMCONNECT_CLOUD_STATE_ARRAY_WIDTH = 64
	SIMCONNECT_CLOUD_STATE_ARRAY_SIZE  = SIMCONNECT_CLOUD_STATE_ARRAY_WIDTH * SIMCONNECT_CLOUD_STATE_ARRAY_WIDTH

	// VOR flags
	SIMCONNECT_RECV_ID_VOR_LIST_HAS_NAV_SIGNAL  = uint32(0x00000001)
	SIMCONNECT_RECV_ID_VOR_LIST_HAS_LOCALIZER   = uint32(0x00000002)
	SIMCONNECT_RECV_ID_VOR_LIST_HAS_GLIDE_SLOPE = uint32(0x00000004)
	SIMCONNECT_RECV_ID_VOR_LIST_HAS_DME         = uint32(0x00000008)

	// Waypoint flags
	SIMCONNECT_WAYPOINT_NONE                   = uint32(0x00)
	SIMCONNECT_WAYPOINT_SPEED_REQUESTED        = uint32(0x04)
	SIMCONNECT_WAYPOINT_THROTTLE_REQUESTED     = uint32(0x08)
	SIMCONNECT_WAYPOINT_COMPUTE_VERTICAL_SPEED = uint32(0x10)
	SIMCONNECT_WAYPOINT_ALTITUDE_IS_AGL        = uint32(0x20)
	SIMCONNECT_WAYPOINT_ON_GROUND              = uint32(0x00100000)
	SIMCONNECT_WAYPOINT_REVERSE                = uint32(0x00200000)
	SIMCONNECT_WAYPOINT_WRAP_TO_FIRST          = uint32(0x00400000)
	SIMCONNECT_WAYPOINT_ALWAYS_BACKUP          = uint32(0x00800000)
	SIMCONNECT_WAYPOINT_KEEP_LAST_HEADING      = uint32(0x01000000)
	SIMCONNECT_WAYPOINT_YIELD_TO_USER          = uint32(0x02000000)
	SIMCONNECT_WAYPOINT_CAN_REVERSE            = uint32(0x04000000)

	// Event flags
	SIMCONNECT_EVENT_FLAG_DEFAULT             = uint32(0x00000000)
	SIMCONNECT_EVENT_FLAG_FAST_REPEAT_TIMER   = uint32(0x00000001)
	SIMCONNECT_EVENT_FLAG_SLOW_REPEAT_TIMER   = uint32(0x00000002)
	SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY = uint32(0x00000010)

	// Data request flags
	SIMCONNECT_DATA_REQUEST_FLAG_DEFAULT = uint32(0x00000000)
	SIMCONNECT_DATA_REQUEST_FLAG_CHANGED = uint32(0x00000001)
	SIMCONNECT_DATA_REQUEST_FLAG_TAGGED  = uint32(0x00000002)

	// Data set flags
	SIMCONNECT_DATA_SET_FLAG_DEFAULT = uint32(0x00000000)
	SIMCONNECT_DATA_SET_FLAG_TAGGED  = uint32(0x00000001)

	// Create client data flags
	SIMCONNECT_CREATE_CLIENT_DATA_FLAG_DEFAULT   = uint32(0x00000000)
	SIMCONNECT_CREATE_CLIENT_DATA_FLAG_READ_ONLY = uint32(0x00000001)

	// Client data request flags
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_DEFAULT = uint32(0x00000000)
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_CHANGED = uint32(0x00000001)
	SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_TAGGED  = uint32(0x00000002)

	// Client data set flags
	SIMCONNECT_CLIENT_DATA_SET_FLAG_DEFAULT = uint32(0x00000000)
	SIMCONNECT_CLIENT_DATA_SET_FLAG_TAGGED  = uint32(0x00000001)

	// View system event data flags
	SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_COCKPIT_2D      = uint32(0x00000001)
	SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_COCKPIT_VIRTUAL = uint32(0x00000002)
	SIMCONNECT_VIEW_SYSTEM_EVENT_DATA_ORTHOGONAL      = uint32(0x00000004)

	// Sound system event data flags
	SIMCONNECT_SOUND_SYSTEM_EVENT_DATA_MASTER = uint32(0x00000001)

	// Comm bus broadcast targets
	SIMCONNECT_COMM_BUS_BROADCAST_TO_JS                   = uint32(1 << 0)
	SIMCONNECT_COMM_BUS_BROADCAST_TO_WASM                 = uint32(1 << 1)
	SIMCONNECT_COMM_BUS_BROADCAST_TO_SIMCONNECT           = uint32(1 << 3)
	SIMCONNECT_COMM_BUS_BROADCAST_TO_SIMCONNECT_SELF_CALL = uint32(1 << 4)
	SIMCONNECT_COMM_BUS_BROADCAST_TO_DEFAULT              = SIMCONNECT_COMM_BUS_BROADCAST_TO_JS | SIMCONNECT_COMM_BUS_BROADCAST_TO_WASM | SIMCONNECT_COMM_BUS_BROADCAST_TO_SIMCONNECT
	SIMCONNECT_COMM_BUS_BROADCAST_TO_ALL_SIMCONNECT       = SIMCONNECT_COMM_BUS_BROADCAST_TO_SIMCONNECT | SIMCONNECT_COMM_BUS_BROADCAST_TO_SIMCONNECT_SELF_CALL
	SIMCONNECT_COMM_BUS_BROADCAST_TO_ALL                  = SIMCONNECT_COMM_BUS_BROADCAST_TO_JS | SIMCONNECT_COMM_BUS_BROADCAST_TO_WASM | SIMCONNECT_COMM_BUS_BROADCAST_TO_SIMCONNECT | SIMCONNECT_COMM_BUS_BROADCAST_TO_SIMCONNECT_SELF_CALL

	// Camera data mask flags
	SIMCONNECT_CAMERA_DATA_MASK_NONE         = uint32(0)
	SIMCONNECT_CAMERA_DATA_MASK_POSITION     = uint32(1 << 0)
	SIMCONNECT_CAMERA_DATA_MASK_ROTATION     = uint32(1 << 1)
	SIMCONNECT_CAMERA_DATA_MASK_TARGETED     = uint32(1 << 2)
	SIMCONNECT_CAMERA_DATA_MASK_FOV          = uint32(1 << 3)
	SIMCONNECT_CAMERA_DATA_MASK_ALL_ROTATION = SIMCONNECT_CAMERA_DATA_MASK_POSITION | SIMCONNECT_CAMERA_DATA_MASK_ROTATION | SIMCONNECT_CAMERA_DATA_MASK_FOV
	SIMCONNECT_CAMERA_DATA_MASK_ALL_TARGETED = SIMCONNECT_CAMERA_DATA_MASK_POSITION | SIMCONNECT_CAMERA_DATA_MASK_TARGETED | SIMCONNECT_CAMERA_DATA_MASK_FOV

	// Camera flags
	SIMCONNECT_CAMERA_FLAG_INTERACTION  = uint32(0x01)
	SIMCONNECT_CAMERA_FLAG_ABOVE_GROUND = uint32(0x02)
)
