//go:build windows

//go:generate stringer -type=SIMCONNECT_RECV_ID,SIMCONNECT_EXCEPTION

package bindings

// SIMCONNECT_RECV_ID identifies the type of data in a received packet.
type SIMCONNECT_RECV_ID uint32

const (
	SIMCONNECT_RECV_ID_NULL SIMCONNECT_RECV_ID = iota
	SIMCONNECT_RECV_ID_EXCEPTION
	SIMCONNECT_RECV_ID_OPEN
	SIMCONNECT_RECV_ID_QUIT
	SIMCONNECT_RECV_ID_EVENT
	SIMCONNECT_RECV_ID_EVENT_OBJECT_ADDREMOVE
	SIMCONNECT_RECV_ID_EVENT_FILENAME
	SIMCONNECT_RECV_ID_EVENT_FRAME
	SIMCONNECT_RECV_ID_SIMOBJECT_DATA
	SIMCONNECT_RECV_ID_SIMOBJECT_DATA_BYTYPE
	SIMCONNECT_RECV_ID_WEATHER_OBSERVATION
	SIMCONNECT_RECV_ID_CLOUD_STATE
	SIMCONNECT_RECV_ID_ASSIGNED_OBJECT_ID
	SIMCONNECT_RECV_ID_RESERVED_KEY
	SIMCONNECT_RECV_ID_CUSTOM_ACTION
	SIMCONNECT_RECV_ID_SYSTEM_STATE
	SIMCONNECT_RECV_ID_CLIENT_DATA
	SIMCONNECT_RECV_ID_EVENT_WEATHER_MODE
	SIMCONNECT_RECV_ID_AIRPORT_LIST
	SIMCONNECT_RECV_ID_VOR_LIST
	SIMCONNECT_RECV_ID_NDB_LIST
	SIMCONNECT_RECV_ID_WAYPOINT_LIST
	SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SERVER_STARTED
	SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_CLIENT_STARTED
	SIMCONNECT_RECV_ID_EVENT_MULTIPLAYER_SESSION_ENDED
	SIMCONNECT_RECV_ID_EVENT_RACE_END
	SIMCONNECT_RECV_ID_EVENT_RACE_LAP
	SIMCONNECT_RECV_ID_EVENT_EX1
	SIMCONNECT_RECV_ID_FACILITY_DATA
	SIMCONNECT_RECV_ID_FACILITY_DATA_END
	SIMCONNECT_RECV_ID_FACILITY_MINIMAL_LIST
	SIMCONNECT_RECV_ID_JETWAY_DATA
	SIMCONNECT_RECV_ID_CONTROLLERS_LIST
	SIMCONNECT_RECV_ID_ACTION_CALLBACK
	SIMCONNECT_RECV_ID_ENUMERATE_INPUT_EVENTS
	SIMCONNECT_RECV_ID_GET_INPUT_EVENT
	SIMCONNECT_RECV_ID_SUBSCRIBE_INPUT_EVENT
	SIMCONNECT_RECV_ID_ENUMERATE_INPUT_EVENT_PARAMS
	SIMCONNECT_RECV_ID_ENUMERATE_SIMOBJECT_AND_LIVERY_LIST
	SIMCONNECT_RECV_ID_FLOW_EVENT
	SIMCONNECT_RECV_ID_CAMERA_DATA
	SIMCONNECT_RECV_ID_CAMERA_STATUS
	SIMCONNECT_RECV_ID_CAMERA_DEFINITION_LIST
	SIMCONNECT_RECV_ID_COMM_BUS
	SIMCONNECT_RECV_ID_CAMERA_WORLD_LOCKER
)

// SIMCONNECT_DATATYPE specifies the data type of a simulation variable.
type SIMCONNECT_DATATYPE int32

const (
	SIMCONNECT_DATATYPE_INVALID SIMCONNECT_DATATYPE = iota
	SIMCONNECT_DATATYPE_INT32
	SIMCONNECT_DATATYPE_INT64
	SIMCONNECT_DATATYPE_FLOAT32
	SIMCONNECT_DATATYPE_FLOAT64
	SIMCONNECT_DATATYPE_STRING8
	SIMCONNECT_DATATYPE_STRING32
	SIMCONNECT_DATATYPE_STRING64
	SIMCONNECT_DATATYPE_STRING128
	SIMCONNECT_DATATYPE_STRING256
	SIMCONNECT_DATATYPE_STRING260
	SIMCONNECT_DATATYPE_STRINGV
	SIMCONNECT_DATATYPE_INITPOSITION
	SIMCONNECT_DATATYPE_MARKERSTATE
	SIMCONNECT_DATATYPE_WAYPOINT
	SIMCONNECT_DATATYPE_LATLONALT
	SIMCONNECT_DATATYPE_XYZ
	SIMCONNECT_DATATYPE_INT8
	SIMCONNECT_DATATYPE_MAX
)

// SIMCONNECT_EXCEPTION error codes returned in SIMCONNECT_RECV_EXCEPTION.
type SIMCONNECT_EXCEPTION uint32

const (
	SIMCONNECT_EXCEPTION_NONE SIMCONNECT_EXCEPTION = iota
	SIMCONNECT_EXCEPTION_ERROR
	SIMCONNECT_EXCEPTION_SIZE_MISMATCH
	SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID
	SIMCONNECT_EXCEPTION_UNOPENED
	SIMCONNECT_EXCEPTION_VERSION_MISMATCH
	SIMCONNECT_EXCEPTION_TOO_MANY_GROUPS
	SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED
	SIMCONNECT_EXCEPTION_TOO_MANY_EVENT_NAMES
	SIMCONNECT_EXCEPTION_EVENT_ID_DUPLICATE
	SIMCONNECT_EXCEPTION_TOO_MANY_MAPS
	SIMCONNECT_EXCEPTION_TOO_MANY_OBJECTS
	SIMCONNECT_EXCEPTION_TOO_MANY_REQUESTS
	SIMCONNECT_EXCEPTION_WEATHER_INVALID_PORT
	SIMCONNECT_EXCEPTION_WEATHER_INVALID_METAR
	SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_GET_OBSERVATION
	SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_CREATE_STATION
	SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_REMOVE_STATION
	SIMCONNECT_EXCEPTION_INVALID_DATA_TYPE
	SIMCONNECT_EXCEPTION_INVALID_DATA_SIZE
	SIMCONNECT_EXCEPTION_DATA_ERROR
	SIMCONNECT_EXCEPTION_INVALID_ARRAY
	SIMCONNECT_EXCEPTION_CREATE_OBJECT_FAILED
	SIMCONNECT_EXCEPTION_LOAD_FLIGHTPLAN_FAILED
	SIMCONNECT_EXCEPTION_OPERATION_INVALID_FOR_OBJECT_TYPE
	SIMCONNECT_EXCEPTION_ILLEGAL_OPERATION
	SIMCONNECT_EXCEPTION_ALREADY_SUBSCRIBED
	SIMCONNECT_EXCEPTION_INVALID_ENUM
	SIMCONNECT_EXCEPTION_DEFINITION_ERROR
	SIMCONNECT_EXCEPTION_DUPLICATE_ID
	SIMCONNECT_EXCEPTION_DATUM_ID
	SIMCONNECT_EXCEPTION_OUT_OF_BOUNDS
	SIMCONNECT_EXCEPTION_ALREADY_CREATED
	SIMCONNECT_EXCEPTION_OBJECT_OUTSIDE_REALITY_BUBBLE
	SIMCONNECT_EXCEPTION_OBJECT_CONTAINER
	SIMCONNECT_EXCEPTION_OBJECT_AI
	SIMCONNECT_EXCEPTION_OBJECT_ATC
	SIMCONNECT_EXCEPTION_OBJECT_SCHEDULE
	SIMCONNECT_EXCEPTION_JETWAY_DATA
	SIMCONNECT_EXCEPTION_ACTION_NOT_FOUND
	SIMCONNECT_EXCEPTION_NOT_AN_ACTION
	SIMCONNECT_EXCEPTION_INCORRECT_ACTION_PARAMS
	SIMCONNECT_EXCEPTION_GET_INPUT_EVENT_FAILED
	SIMCONNECT_EXCEPTION_SET_INPUT_EVENT_FAILED
	SIMCONNECT_EXCEPTION_EVENT_NAME_RESERVED
	SIMCONNECT_EXCEPTION_INTERNAL
	SIMCONNECT_EXCEPTION_CAMERA_API
)

// SIMCONNECT_SIMOBJECT_TYPE identifies the type of simulation object.
type SIMCONNECT_SIMOBJECT_TYPE uint32

const (
	SIMCONNECT_SIMOBJECT_TYPE_USER            SIMCONNECT_SIMOBJECT_TYPE = 0
	SIMCONNECT_SIMOBJECT_TYPE_USER_AIRCRAFT   SIMCONNECT_SIMOBJECT_TYPE = 0
	SIMCONNECT_SIMOBJECT_TYPE_ALL             SIMCONNECT_SIMOBJECT_TYPE = 1
	SIMCONNECT_SIMOBJECT_TYPE_AIRCRAFT        SIMCONNECT_SIMOBJECT_TYPE = 2
	SIMCONNECT_SIMOBJECT_TYPE_HELICOPTER      SIMCONNECT_SIMOBJECT_TYPE = 3
	SIMCONNECT_SIMOBJECT_TYPE_BOAT            SIMCONNECT_SIMOBJECT_TYPE = 4
	SIMCONNECT_SIMOBJECT_TYPE_GROUND          SIMCONNECT_SIMOBJECT_TYPE = 5
	SIMCONNECT_SIMOBJECT_TYPE_HOT_AIR_BALLOON SIMCONNECT_SIMOBJECT_TYPE = 6
	SIMCONNECT_SIMOBJECT_TYPE_ANIMAL          SIMCONNECT_SIMOBJECT_TYPE = 7
	SIMCONNECT_SIMOBJECT_TYPE_USER_AVATAR     SIMCONNECT_SIMOBJECT_TYPE = 8
	SIMCONNECT_SIMOBJECT_TYPE_USER_CURRENT    SIMCONNECT_SIMOBJECT_TYPE = 9
)

// SIMCONNECT_STATE on/off state.
type SIMCONNECT_STATE uint32

const (
	SIMCONNECT_STATE_OFF SIMCONNECT_STATE = iota
	SIMCONNECT_STATE_ON
)

// SIMCONNECT_PERIOD controls how often data is sent.
type SIMCONNECT_PERIOD uint32

const (
	SIMCONNECT_PERIOD_NEVER SIMCONNECT_PERIOD = iota
	SIMCONNECT_PERIOD_ONCE
	SIMCONNECT_PERIOD_VISUAL_FRAME
	SIMCONNECT_PERIOD_SIM_FRAME
	SIMCONNECT_PERIOD_SECOND
)

// SIMCONNECT_MISSION_END mission result.
type SIMCONNECT_MISSION_END uint32

const (
	SIMCONNECT_MISSION_FAILED SIMCONNECT_MISSION_END = iota
	SIMCONNECT_MISSION_CRASHED
	SIMCONNECT_MISSION_SUCCEEDED
)

// SIMCONNECT_CLIENT_DATA_PERIOD controls how often client data is sent.
type SIMCONNECT_CLIENT_DATA_PERIOD uint32

const (
	SIMCONNECT_CLIENT_DATA_PERIOD_NEVER SIMCONNECT_CLIENT_DATA_PERIOD = iota
	SIMCONNECT_CLIENT_DATA_PERIOD_ONCE
	SIMCONNECT_CLIENT_DATA_PERIOD_VISUAL_FRAME
	SIMCONNECT_CLIENT_DATA_PERIOD_ON_SET
	SIMCONNECT_CLIENT_DATA_PERIOD_SECOND
)

// SIMCONNECT_TEXT_TYPE controls text display style.
type SIMCONNECT_TEXT_TYPE uint32

const (
	SIMCONNECT_TEXT_TYPE_SCROLL_BLACK   SIMCONNECT_TEXT_TYPE = 0
	SIMCONNECT_TEXT_TYPE_SCROLL_WHITE   SIMCONNECT_TEXT_TYPE = 1
	SIMCONNECT_TEXT_TYPE_SCROLL_RED     SIMCONNECT_TEXT_TYPE = 2
	SIMCONNECT_TEXT_TYPE_SCROLL_GREEN   SIMCONNECT_TEXT_TYPE = 3
	SIMCONNECT_TEXT_TYPE_SCROLL_BLUE    SIMCONNECT_TEXT_TYPE = 4
	SIMCONNECT_TEXT_TYPE_SCROLL_YELLOW  SIMCONNECT_TEXT_TYPE = 5
	SIMCONNECT_TEXT_TYPE_SCROLL_MAGENTA SIMCONNECT_TEXT_TYPE = 6
	SIMCONNECT_TEXT_TYPE_SCROLL_CYAN    SIMCONNECT_TEXT_TYPE = 7
	SIMCONNECT_TEXT_TYPE_PRINT_BLACK    SIMCONNECT_TEXT_TYPE = 0x0100
	SIMCONNECT_TEXT_TYPE_PRINT_WHITE    SIMCONNECT_TEXT_TYPE = 0x0101
	SIMCONNECT_TEXT_TYPE_PRINT_RED      SIMCONNECT_TEXT_TYPE = 0x0102
	SIMCONNECT_TEXT_TYPE_PRINT_GREEN    SIMCONNECT_TEXT_TYPE = 0x0103
	SIMCONNECT_TEXT_TYPE_PRINT_BLUE     SIMCONNECT_TEXT_TYPE = 0x0104
	SIMCONNECT_TEXT_TYPE_PRINT_YELLOW   SIMCONNECT_TEXT_TYPE = 0x0105
	SIMCONNECT_TEXT_TYPE_PRINT_MAGENTA  SIMCONNECT_TEXT_TYPE = 0x0106
	SIMCONNECT_TEXT_TYPE_PRINT_CYAN     SIMCONNECT_TEXT_TYPE = 0x0107
	SIMCONNECT_TEXT_TYPE_MENU           SIMCONNECT_TEXT_TYPE = 0x0200
)

// SIMCONNECT_TEXT_RESULT text display result.
type SIMCONNECT_TEXT_RESULT uint32

const (
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_1  SIMCONNECT_TEXT_RESULT = 0
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_2  SIMCONNECT_TEXT_RESULT = 1
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_3  SIMCONNECT_TEXT_RESULT = 2
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_4  SIMCONNECT_TEXT_RESULT = 3
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_5  SIMCONNECT_TEXT_RESULT = 4
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_6  SIMCONNECT_TEXT_RESULT = 5
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_7  SIMCONNECT_TEXT_RESULT = 6
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_8  SIMCONNECT_TEXT_RESULT = 7
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_9  SIMCONNECT_TEXT_RESULT = 8
	SIMCONNECT_TEXT_RESULT_MENU_SELECT_10 SIMCONNECT_TEXT_RESULT = 9
	SIMCONNECT_TEXT_RESULT_DISPLAYED      SIMCONNECT_TEXT_RESULT = 0x00010000
	SIMCONNECT_TEXT_RESULT_QUEUED         SIMCONNECT_TEXT_RESULT = 0x00010001
	SIMCONNECT_TEXT_RESULT_REMOVED        SIMCONNECT_TEXT_RESULT = 0x00010002
	SIMCONNECT_TEXT_RESULT_REPLACED       SIMCONNECT_TEXT_RESULT = 0x00010003
	SIMCONNECT_TEXT_RESULT_TIMEOUT        SIMCONNECT_TEXT_RESULT = 0x00010004
)

// SIMCONNECT_WEATHER_MODE weather mode.
type SIMCONNECT_WEATHER_MODE uint32

const (
	SIMCONNECT_WEATHER_MODE_THEME SIMCONNECT_WEATHER_MODE = iota
	SIMCONNECT_WEATHER_MODE_RWW
	SIMCONNECT_WEATHER_MODE_CUSTOM
	SIMCONNECT_WEATHER_MODE_GLOBAL
)

// SIMCONNECT_FACILITY_LIST_TYPE type of facility list.
type SIMCONNECT_FACILITY_LIST_TYPE uint32

const (
	SIMCONNECT_FACILITY_LIST_TYPE_AIRPORT SIMCONNECT_FACILITY_LIST_TYPE = iota
	SIMCONNECT_FACILITY_LIST_TYPE_WAYPOINT
	SIMCONNECT_FACILITY_LIST_TYPE_NDB
	SIMCONNECT_FACILITY_LIST_TYPE_VOR
	SIMCONNECT_FACILITY_LIST_TYPE_COUNT
)

// SIMCONNECT_FACILITY_DATA_TYPE type of facility data element.
type SIMCONNECT_FACILITY_DATA_TYPE uint32

const (
	SIMCONNECT_FACILITY_DATA_AIRPORT SIMCONNECT_FACILITY_DATA_TYPE = iota
	SIMCONNECT_FACILITY_DATA_RUNWAY
	SIMCONNECT_FACILITY_DATA_START
	SIMCONNECT_FACILITY_DATA_FREQUENCY
	SIMCONNECT_FACILITY_DATA_HELIPAD
	SIMCONNECT_FACILITY_DATA_APPROACH
	SIMCONNECT_FACILITY_DATA_APPROACH_TRANSITION
	SIMCONNECT_FACILITY_DATA_APPROACH_LEG
	SIMCONNECT_FACILITY_DATA_FINAL_APPROACH_LEG
	SIMCONNECT_FACILITY_DATA_MISSED_APPROACH_LEG
	SIMCONNECT_FACILITY_DATA_DEPARTURE
	SIMCONNECT_FACILITY_DATA_ARRIVAL
	SIMCONNECT_FACILITY_DATA_RUNWAY_TRANSITION
	SIMCONNECT_FACILITY_DATA_ENROUTE_TRANSITION
	SIMCONNECT_FACILITY_DATA_TAXI_POINT
	SIMCONNECT_FACILITY_DATA_TAXI_PARKING
	SIMCONNECT_FACILITY_DATA_TAXI_PATH
	SIMCONNECT_FACILITY_DATA_TAXI_NAME
	SIMCONNECT_FACILITY_DATA_JETWAY
	SIMCONNECT_FACILITY_DATA_VOR
	SIMCONNECT_FACILITY_DATA_NDB
	SIMCONNECT_FACILITY_DATA_WAYPOINT
	SIMCONNECT_FACILITY_DATA_ROUTE
	SIMCONNECT_FACILITY_DATA_PAVEMENT
	SIMCONNECT_FACILITY_DATA_APPROACH_LIGHTS
	SIMCONNECT_FACILITY_DATA_VASI
	SIMCONNECT_FACILITY_DATA_VDGS
	SIMCONNECT_FACILITY_DATA_HOLDING_PATTERN
	SIMCONNECT_FACILITY_DATA_TAXI_PARKING_AIRLINE
)

// SIMCONNECT_INPUT_EVENT_TYPE type of input event value.
type SIMCONNECT_INPUT_EVENT_TYPE uint32

const (
	SIMCONNECT_INPUT_EVENT_TYPE_DOUBLE SIMCONNECT_INPUT_EVENT_TYPE = iota
	SIMCONNECT_INPUT_EVENT_TYPE_STRING
)

// SIMCONNECT_FLOW_EVENT flight flow events.
type SIMCONNECT_FLOW_EVENT uint32

const (
	SIMCONNECT_FLOW_EVENT_NONE SIMCONNECT_FLOW_EVENT = iota
	SIMCONNECT_FLOW_EVENT_FLT_LOAD
	SIMCONNECT_FLOW_EVENT_FLT_LOADED
	SIMCONNECT_FLOW_EVENT_TELEPORT_START
	SIMCONNECT_FLOW_EVENT_TELEPORT_DONE
	SIMCONNECT_FLOW_EVENT_BACK_ON_TRACK_START
	SIMCONNECT_FLOW_EVENT_BACK_ON_TRACK_DONE
	SIMCONNECT_FLOW_EVENT_SKIP_START
	SIMCONNECT_FLOW_EVENT_SKIP_DONE
	SIMCONNECT_FLOW_EVENT_BACK_TO_MAIN_MENU
	SIMCONNECT_FLOW_EVENT_RTC_START
	SIMCONNECT_FLOW_EVENT_RTC_END
	SIMCONNECT_FLOW_EVENT_REPLAY_START
	SIMCONNECT_FLOW_EVENT_REPLAY_END
	SIMCONNECT_FLOW_EVENT_FLIGHT_START
	SIMCONNECT_FLOW_EVENT_FLIGHT_END
	SIMCONNECT_FLOW_EVENT_PLANE_CRASH
)

// SIMCONNECT_POSITION_REFERENTIAL reference frame for camera position.
type SIMCONNECT_POSITION_REFERENTIAL uint32

const (
	SIMCONNECT_POSITION_REFERENTIAL_NONE SIMCONNECT_POSITION_REFERENTIAL = iota
	SIMCONNECT_POSITION_REFERENTIAL_SIMOBJECT
	SIMCONNECT_POSITION_REFERENTIAL_WORLD
	SIMCONNECT_POSITION_REFERENTIAL_EYEPOINT
	SIMCONNECT_POSITION_REFERENTIAL_SIMOBJECT_DATUM
)

// SIMCONNECT_CAMERA_WORLD_LOCKER_STATUS status of the world locker.
type SIMCONNECT_CAMERA_WORLD_LOCKER_STATUS uint32

const (
	SIMCONNECT_CAMERA_WORLD_LOCKER_STATUS_NONE SIMCONNECT_CAMERA_WORLD_LOCKER_STATUS = iota
	SIMCONNECT_CAMERA_WORLD_LOCKER_STATUS_START
	SIMCONNECT_CAMERA_WORLD_LOCKER_STATUS_SUCCESS
	SIMCONNECT_CAMERA_WORLD_LOCKER_STATUS_CANCEL
	SIMCONNECT_CAMERA_WORLD_LOCKER_STATUS_FAIL
)

// SIMCONNECT_CAMERA_AVAILABILITY camera acquisition state.
type SIMCONNECT_CAMERA_AVAILABILITY uint32

const (
	SIMCONNECT_CAMERA_NOT_ACQUIRED SIMCONNECT_CAMERA_AVAILABILITY = iota
	SIMCONNECT_CAMERA_ACQUIRED
	SIMCONNECT_CAMERA_ACQUIRED_BY_OTHER
	SIMCONNECT_CAMERA_USER_DISABLED
)

// Client-defined ID types (typedef DWORD in C)
type SIMCONNECT_OBJECT_ID = uint32
type SIMCONNECT_NOTIFICATION_GROUP_ID = uint32
type SIMCONNECT_INPUT_GROUP_ID = uint32
type SIMCONNECT_DATA_DEFINITION_ID = uint32
type SIMCONNECT_DATA_REQUEST_ID = uint32
type SIMCONNECT_CLIENT_EVENT_ID = uint32
type SIMCONNECT_CLIENT_DATA_ID = uint32
type SIMCONNECT_CLIENT_DATA_DEFINITION_ID = uint32

// Flag types (typedef DWORD in C)
type SIMCONNECT_VOR_FLAGS = uint32
type SIMCONNECT_WAYPOINT_FLAGS = uint32
type SIMCONNECT_EVENT_FLAG = uint32
type SIMCONNECT_DATA_REQUEST_FLAG = uint32
type SIMCONNECT_DATA_SET_FLAG = uint32
type SIMCONNECT_CREATE_CLIENT_DATA_FLAG = uint32
type SIMCONNECT_CLIENT_DATA_REQUEST_FLAG = uint32
type SIMCONNECT_CLIENT_DATA_SET_FLAG = uint32
type SIMCONNECT_VIEW_SYSTEM_EVENT_DATA = uint32
type SIMCONNECT_SOUND_SYSTEM_EVENT_DATA = uint32
type SIMCONNECT_COMM_BUS_BROADCAST_TO = uint32
type SIMCONNECT_CAMERA_DATA_MASK = uint32
type SIMCONNECT_CAMERA_FLAG = uint32
